org: jurmanec # "org" ensures this Service is used with the correct Serverless Framework Access Key.
service: order-management-dashboard-backend # "service" is the name of this project. This will also be added to your AWS resource names.
provider:
  name: aws
  runtime: nodejs20.x
  region: ${opt:region, 'us-east-1'}
  iam:
    role:
      statements:
        # API
        - Effect: Allow # getOrders
          Action:
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - arn:aws:dynamodb:${aws:region}:*:table/Orders-${opt:stage, self:provider.stage}
            - arn:aws:dynamodb:${aws:region}:*:table/Orders-${opt:stage, self:provider.stage}/index/StatusIndex
        - Effect: Allow # updateOrder
          Action:
            - dynamodb:UpdateItem
          Resource:
            - arn:aws:dynamodb:${aws:region}:*:table/Orders-${opt:stage, self:provider.stage}
        - Effect: Allow # streamProcessor
          Action:
            - dynamodb:DescribeStream
            - dynamodb:GetRecords
            - dynamodb:GetShardIterator
            - dynamodb:ListStreams
          Resource: arn:aws:dynamodb:${aws:region}:*:table/Orders-${opt:stage, self:provider.stage}/stream/*
        - Effect: Allow
          Action:
            - execute-api:ManageConnections
          Resource: '*'
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:${aws:region}:*:table/Connections-${opt:stage, self:provider.stage}
        # Websocket
        - Effect: Allow # websocketUpdate, streamProcessor
          Action:
            - execute-api:ManageConnections
          Resource: '*'
        - Effect: Allow # connect
          Action:
            - dynamodb:PutItem
          Resource:
            - arn:aws:dynamodb:${aws:region}:*:table/Connections-${opt:stage, self:provider.stage}
        - Effect: Allow # disconnnect
          Action:
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:${aws:region}:*:table/Connections-${opt:stage, self:provider.stage}
  environment:
    STAGE: ${opt:stage, self:provider.stage} 
    ORDERS_TABLE: Orders-${opt:stage, self:provider.stage} 
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com
custom:
  stream:
    dev: '2025-08-17T01:21:53.702'
    qa: '2025-08-17T01:22:01.745'
functions:
  getOrders:
    handler: src/get-orders/index.handler
    events:
      - http:
          path: /orders
          method: get
          cors: true
  updateOrder: 
    handler: src/update-order/index.handler
    events:
      - http:
          path: /orders/{order_id}
          method: put
          cors: true
  websocketUpdate:
    handler: src/websocket-update/index.handler
    events:
      - websocket:
          route: $default
  streamProcessor:
    handler: src/stream-processor/index.handler
    events:
      - stream:
          arn: "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/\
            Orders-${opt:stage, self:provider.stage}/stream/${self:custom.stream.${opt:stage, self:provider.stage}}"
          batchSize: 10
  connect:
    description: 'Adds entry to Connections table on client websocket connect'
    handler: src/connect/index.handler
    events:
      - websocket:
          route: $connect
  disconnect:
    description: 'Deletes entry from Connections table on client websocket disconnect'
    handler: src/disconnect/index.handler
    events:
      - websocket:
          route: $disconnect
  # getInventory:
  #   handler: src/get-inventory/index.handler
  #   events:
  #     - http:
  #         path: /inventory
  #         method: get
  #         cors: true
  #   iamRoleStatements:
  #     - Effect: Allow
  #       Action:
  #         - dynamodb:Scan
  #       Resource:
  #         - arn:aws:dynamodb:${self:provider.region}:*:table/Inventory
# plugins:
#   - serverless-websockets-plugin
# Tables defined in iac/setup.sh