name: Deploy Backend and Frontend
on:
  push:
    branches: [main]
jobs:
  # deploy-backend:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: backend
  #   outputs:
  #     api_url: ${{ steps.set-urls.outputs.API_URL }}
  #     websocket_url: ${{ steps.set-urls.outputs.WEBSOCKET_URL }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #     - run: npm install
  #     - run: npm install -g serverless
  #     - run: serverless deploy
  #       env:
  #         SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }} 
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #     - name: Output API URLs
  #       id: set-urls
  #       env:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
  #       run: |
  #         echo "API_URL=$(serverless info --verbose 2>&1 | grep ServiceEndpoint: | awk '{print $2}')" >> $GITHUB_OUTPUT
  #         echo "WEBSOCKET_URL=$(serverless info --verbose 2>&1 | grep ServiceEndpointWebsocket: | awk '{print $2}')" >> $GITHUB_OUTPUT
  deploy-frontend:
    runs-on: ubuntu-latest
    # needs: deploy-backend
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm install
      - name: Build Next.js App
        run: npm run build
        env:
          # NEXT_PUBLIC_API_URL: ${{ needs.deploy-backend.outputs.api_url }}
          # NEXT_PUBLIC_WEBSOCKET_URL: ${{ needs.deploy-backend.outputs.websocket_url }}
          NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_WEBSOCKET_URL: ${{ vars.NEXT_PUBLIC_WEBSOCKET_URL }}
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./frontend