name: Deploy Backend and Frontend
on:
  push:
    branches: [main]
permissions:
  contents: write  # Grants read and write access to repository contents
jobs:
  deploy-backend-dev:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm install -g serverless
      - name: Deploy Backend to Dev
        run: serverless deploy --stage dev
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }} 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  deploy-backend-qa:
    runs-on: ubuntu-latest
    needs: deploy-backend-dev
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm install -g serverless
      - name: Deploy Backend to QA
        run: serverless deploy --stage qa
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  sync-branches-dev: # hybrid trunk-based / git-based for aws amplify
    needs: [ deploy-backend-dev ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper branch syncing
      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
      - name: Sync dev branch
        run: |
          git checkout dev || git checkout -b dev
          git merge main --no-edit
          git push origin dev
  sync-branches-qa: # hybrid trunk-based / git-based for aws amplify
    needs: [ deploy-backend-qa ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper branch syncing
      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
      - name: Sync qa branch
        run: |
          git checkout qa || git checkout -b qa
          git merge main --no-edit
          git push origin qa
  # deploy-frontend: # vercel
  #   runs-on: ubuntu-latest
  #   needs: deploy-backend
  #   defaults:
  #     run:
  #       working-directory: frontend
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #     - name: Install Dependencies
  #       run: npm install
  #     - name: Build Next.js App
  #       run: npm run build
  #       env:
  #         NEXT_PUBLIC_API_URL: ${{ needs.deploy-backend.outputs.api_url }}
  #         NEXT_PUBLIC_WEBSOCKET_URL: ${{ needs.deploy-backend.outputs.websocket_url }}
  #     - name: Deploy to Vercel
  #       uses: amondnet/vercel-action@v25
  #       with:
  #         vercel-token: ${{ secrets.VERCEL_TOKEN }}
  #         vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
  #         vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
